SELECT DISTINCT city FROM STATION WHERE city LIKE 'a%';
SELECT DISTINCT city FROM STATION WHERE city LIKE 'e%';
SELECT DISTINCT city FROM STATION WHERE city LIKE 'i%';
SELECT DISTINCT city FROM STATION WHERE city LIKE 'o%';
SELECT DISTINCT city FROM STATION WHERE city LIKE 'u%';